using Content.Client.RichText;
using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.NewsPaper.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;

namespace Content.Client._Floof.NewsPaper;

[GenerateTypedNameReferences]
public sealed partial class NewspaperPrinterWindow : FancyWindow
{
    public event Action<string>? OnPrint;

    private int _maxInputLength = 10000;

    public NewspaperPrinterWindow()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => Print();

        Input.OnTextChanged += _ =>
        {
            UpdateFillState();
            UpdatePreview();
        };

        Input.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.MultilineTextSubmit)
                return;

            if (PrintButton.Disabled)
                return;

            Print();
            args.Handle();
        };

        UpdateFillState();
        UpdatePreview();
    }

    public void UpdateState(NewspaperPrinterBoundUserInterfaceState state)
    {
        _maxInputLength = state.MaxContentLength;

        UpdateFillState();

        PrintButton.Disabled = !state.CanPrint || Input.TextLength == 0 || Input.TextLength > _maxInputLength;
    }

    private void Print()
    {
        if (PrintButton.Disabled)
            return;

        var text = Rope.Collapse(Input.TextRope);

        if (string.IsNullOrWhiteSpace(text))
            return;

        if (text.Length > _maxInputLength)
            return;

        PrintButton.Disabled = true;

        OnPrint?.Invoke(text);
    }

    private void UpdateFillState()
    {
        var length = Input.TextLength;

        FillStatus.Text = $"{length} / {_maxInputLength}";

        PrintButton.Disabled = length == 0 || length > _maxInputLength;
    }

    private void UpdatePreview()
    {
        var text = Rope.Collapse(Input.TextRope);

        var message = new FormattedMessage();
        message.AddMarkupPermissive(text);

        Preview.SetMessage(message, UserFormattableTags.BaseAllowedTags, new Color(220, 220, 220));
    }
}
