- type: entity
  parent: SmartFridgeCircuitboard
  id: SmartFridgeServiceCircuitboard
  name: Service SmartFridge machine board
  description: A machine printed circuit board for a Service SmartFridge.
  components:
  - type: MachineBoard
    prototype: SmartFridgeService

- type: entity
  parent: BaseComputerCircuitboard
  id: ComputerNewspaperPrinterCircuitboard
  name: news paper printer console board
  description: Write your message to the world in that old fashioned style!
  components:
  - type: Sprite
    state: cpu_service
  - type: StaticPrice
    price: 150
  - type: ComputerBoard
    prototype: ComputerNewspaperPrinter
